plugin: aws_ec2
regions:
  - "us-east-1"
filters:
  tag:app-stack-name: AWS_STACK_NAME
  tag:environment: mlops
  tag:swarm-role: manager
hostnames:
  - "private-ip-address"
compose:
  ansible_user: "'ec2-user'"